# Generated by Django 6.1 on 2026-08-31 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('passed_out', 'Passed Out')], default='active', max_length=20),
        ),
    ]
