# Generated by Django 6.1 on 2026-09-01 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_student_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('passed_out', 'Passed Out'), ('dropped', 'Dropped')], default='active', max_length=20),
        ),
    ]
