# Generated by Django 6.1 on 2026-09-01 14:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_alter_student_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='enrollment',
            options={'ordering': ['-enrolled_on']},
        ),
        migrations.RemoveConstraint(
            model_name='enrollment',
            name='unique_student_semester_enrollment',
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='current_students', to='attendance.semester'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='enrollment', to='attendance.student'),
        ),
    ]
